name: Rølland Transport
favicon: null
layout_spectrum: 0.24013
typography_spectrum: 0.21659
title: Rølland Transport - byggeplasstransport siden 1990
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1f232c'
    - '#505050'
    - '#8692a0'
    - '#a5584e'
  brandStrength: 0.5
  lightness: 0.44157036440446973
  saturation: 0
  rhythmicContrast: 0.3460191306658089
purpose: []
