name: Rølland Transport
favicon: null
layout_spectrum: 0.5592889438848943
typography_spectrum: 0.7773745039012283
title: Rølland Transport - byggeplasstransport siden 1990
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.11593444412574172
  lightness: 0.44157036440446973
  saturation: 0.6369772097095847
  rhythmicContrast: 0.3460191306658089
purpose: []
