title: Rølland Transport - byggeplasstransport siden 1990
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 0.5
  rhythmicContrast: 0.3460191306658089
  brandColors:
    - '#ffffff'
    - '#1f232c'
    - '#505050'
    - '#8692a0'
    - '#a5584e'
  lightness: 0.4415703644044697
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Rølland Transport
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5553191
layout_spectrum: 0.2340426
